# Generated by Django 4.2.7 on 2023-12-01 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_oit', models.IntegerField(verbose_name='Clase de OIT')),
                ('tipo_oit', models.CharField(choices=[('preventivo', 'Mantenimiento Preventivo'), ('correctivo', 'Mantenimiento Correctivo')], max_length=20, verbose_name='Tipo de OIT')),
                ('equipo', models.CharField(max_length=255, verbose_name='Equipo')),
                ('serial', models.CharField(max_length=255, verbose_name='Serial')),
                ('descripcion_eq', models.TextField(verbose_name='Descripción del Equipo')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_inicio_ejecucion', models.DateField(verbose_name='Fecha de Inicio de Ejecución')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('dato_actual_frecuencia', models.DateField(verbose_name='Dato Actual Frecuencia')),
                ('fecha_final_ejecucion', models.DateField(verbose_name='Fecha Final de Ejecución')),
                ('hora_fin', models.TimeField(verbose_name='Hora Fin')),
                ('reporte_tecnico', models.TextField(verbose_name='Reporte Técnico')),
                ('actividad_realizada', models.TextField(verbose_name='Actividad Realizada')),
                ('actividades_pendientes', models.TextField(blank=True, null=True, verbose_name='Actividades Pendientes')),
            ],
            options={
                'verbose_name': 'Orden Interna de Trabajo',
                'verbose_name_plural': 'Ordenes Internas de Trabajo',
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_articulo', models.CharField(max_length=255, verbose_name='Nombre del Artículo')),
                ('referencia_articulo', models.CharField(max_length=255, verbose_name='Referencia del Artículo')),
                ('unidad_medida', models.CharField(max_length=100, verbose_name='Unidad de Medida')),
                ('descripcion', models.TextField(verbose_name='Descripción del Repuesto')),
                ('cantidad_usada', models.PositiveIntegerField(verbose_name='Cantidad Usada')),
                ('oit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='oit.oit')),
            ],
        ),
        migrations.CreateModel(
            name='Falla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte_que_fallo', models.CharField(max_length=255, verbose_name='Parte que Falló')),
                ('causa_del_fallo', models.CharField(max_length=255, verbose_name='Causa del Fallo')),
                ('medida_correctiva', models.TextField(verbose_name='Medida Correctiva')),
                ('oit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallas', to='oit.oit')),
            ],
        ),
    ]
