# Generated by Django 4.2.7 on 2023-12-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='oit',
        ),
        migrations.AddField(
            model_name='oit',
            name='cantidad_usada',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad Usada'),
        ),
        migrations.AddField(
            model_name='oit',
            name='causa_del_fallo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Causa del Fallo'),
        ),
        migrations.AddField(
            model_name='oit',
            name='descripcion_repuesto',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Repuesto'),
        ),
        migrations.AddField(
            model_name='oit',
            name='medida_correctiva',
            field=models.TextField(blank=True, null=True, verbose_name='Medida Correctiva'),
        ),
        migrations.AddField(
            model_name='oit',
            name='nombre_articulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Artículo'),
        ),
        migrations.AddField(
            model_name='oit',
            name='parte_que_fallo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Parte que Falló'),
        ),
        migrations.AddField(
            model_name='oit',
            name='referencia_articulo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia del Artículo'),
        ),
        migrations.AddField(
            model_name='oit',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidad de Medida'),
        ),
        migrations.DeleteModel(
            name='Falla',
        ),
        migrations.DeleteModel(
            name='Repuesto',
        ),
    ]
