# Generated by Django 4.2.7 on 2023-12-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oit', '0003_oit_completado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oit',
            name='clase_oit',
        ),
        migrations.RemoveField(
            model_name='oit',
            name='nombre_articulo',
        ),
        migrations.RemoveField(
            model_name='oit',
            name='referencia_articulo',
        ),
        migrations.AddField(
            model_name='oit',
            name='nombre_repuesto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Repuesto'),
        ),
        migrations.AddField(
            model_name='oit',
            name='numero_oit',
            field=models.IntegerField(default=0, verbose_name='Numero de OIT'),
        ),
        migrations.AddField(
            model_name='oit',
            name='referencia_repuesto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia del Repuesto'),
        ),
    ]
